name: Deploy Landing Zone to Azure

on:
  push:
    branches:
      - dev
      - qa
      - stage
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to destroy"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - stage
          - main

env:
  TF_VAR_environment: ${{ github.ref_name }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  lint:
    name: Terraform Validate & Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: IaC
        run: terraform fmt -check -recursive

      - name: Terraform Init (No backend)
        working-directory: IaC
        run: terraform init -backend=false -input=false -upgrade

      - name: Terraform Validate
        working-directory: IaC
        run: terraform validate

  terraform-plan:
    name: Terraform Plan
    needs: lint
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Branch Name
        run: echo "ENV=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Generate backend.conf
        run: envsubst < IaC/backend-template.conf > IaC/backend.conf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: IaC
        run: terraform init -backend-config="backend.conf"

      - name: Terraform Plan
        working-directory: IaC
        run: terraform plan -out=tfplan -var="env=${{ env.ENV }}"

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: IaC/tfplan

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Branch Name
        run: echo "ENV=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Generate backend.conf
        run: envsubst < IaC/backend-template.conf > IaC/backend.conf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: IaC
        run: terraform init -backend-config="backend.conf"

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: IaC/

      - name: Terraform Apply
        working-directory: IaC
        run: terraform apply -auto-approve tfplan

  terraform-destroy:
    name: Terraform Destroy
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    env:
      ENV: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate backend.conf
        run: envsubst < IaC/backend-template.conf > IaC/backend.conf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: IaC
        run: terraform init -backend-config="backend.conf"

      - name: Terraform Destroy
        working-directory: IaC
        run: terraform destroy -auto-approve -var="env=${{ env.ENV }}"
